from sqlalchemy import Column, Integer, String, Boolean, DateTime, Date, Time
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class Game(Base):
    __tablename__ = 'games'
    id = Column(Integer, primary_key=True)
    date = Column(String(200))
    time = Column(String(200))
    tbd = Column(Boolean, default=False)
    visiting_long_name = Column(String(200), nullable=True)
    visiting_short_name = Column(String(200), nullable=True)
    visiting_full_name = Column(String(200), nullable=True)
    visiting_record = Column(String(200), nullable=True)
    home_long_name = Column(String(200), nullable=True)
    home_short_name = Column(String(200), nullable=True)
    home_full_name = Column(String(200), nullable=True)
    home_record = Column(String(200), nullable=True)
    stadium = Column(String(200), nullable=True)
    city = Column(String(200), nullable=True)
    state = Column(String(200), nullable=True)
    home_last_games = Column(String(200), nullable=True)
    visiting_last_games = Column(String(200), nullable=True)
    visiting_pitcher1_name = Column(String(200), nullable=True)
    visiting_pitcher1_birthdate = Column(String(200), nullable=True)
    visiting_pitcher1_birthplace = Column(String(200), nullable=True)
    visiting_pitcher2_name = Column(String(200), nullable=True)
    visiting_pitcher2_birthdate = Column(String(200), nullable=True)
    visiting_pitcher2_birthplace = Column(String(200), nullable=True)
    visiting_pitcher3_name = Column(String(200), nullable=True)
    visiting_pitcher3_birthdate = Column(String(200), nullable=True)
    visiting_pitcher3_birthplace = Column(String(200), nullable=True)
    visiting_pitcher4_name = Column(String(200), nullable=True)
    visiting_pitcher4_birthdate = Column(String(200), nullable=True)
    visiting_pitcher4_birthplace = Column(String(200), nullable=True)
    visiting_pitcher5_name = Column(String(200), nullable=True)
    visiting_pitcher5_birthdate = Column(String(200), nullable=True)
    visiting_pitcher5_birthplace = Column(String(200), nullable=True)
    visiting_pitcher6_name = Column(String(200), nullable=True)
    visiting_pitcher6_birthdate = Column(String(200), nullable=True)
    visiting_pitcher6_birthplace = Column(String(200), nullable=True)
    visiting_pitcher7_name = Column(String(200), nullable=True)
    visiting_pitcher7_birthdate = Column(String(200), nullable=True)
    visiting_pitcher7_birthplace = Column(String(200), nullable=True)
    visiting_pitcher8_name = Column(String(200), nullable=True)
    visiting_pitcher8_birthdate = Column(String(200), nullable=True)
    visiting_pitcher8_birthplace = Column(String(200), nullable=True)
    visiting_pitcher9_name = Column(String(200), nullable=True)
    visiting_pitcher9_birthdate = Column(String(200), nullable=True)
    visiting_pitcher9_birthplace = Column(String(200), nullable=True) 
    home_pitcher1_name = Column(String(200), nullable=True)
    home_pitcher1_birthdate = Column(String(200), nullable=True)
    home_pitcher1_birthplace = Column(String(200), nullable=True)
    home_pitcher2_name = Column(String(200), nullable=True)
    home_pitcher2_birthdate = Column(String(200), nullable=True)
    home_pitcher2_birthplace = Column(String(200), nullable=True)
    home_pitcher3_name = Column(String(200), nullable=True)
    home_pitcher3_birthdate = Column(String(200), nullable=True)
    home_pitcher3_birthplace = Column(String(200), nullable=True)
    home_pitcher4_name = Column(String(200), nullable=True)
    home_pitcher4_birthdate = Column(String(200), nullable=True)
    home_pitcher4_birthplace = Column(String(200), nullable=True)
    home_pitcher5_name = Column(String(200), nullable=True)
    home_pitcher5_birthdate = Column(String(200), nullable=True)
    home_pitcher5_birthplace = Column(String(200), nullable=True)
    home_pitcher6_name = Column(String(200), nullable=True)
    home_pitcher6_birthdate = Column(String(200), nullable=True)
    home_pitcher6_birthplace = Column(String(200), nullable=True)
    home_pitcher7_name = Column(String(200), nullable=True)
    home_pitcher7_birthdate = Column(String(200), nullable=True)
    home_pitcher7_birthplace = Column(String(200), nullable=True)
    home_pitcher8_name = Column(String(200), nullable=True)
    home_pitcher8_birthdate = Column(String(200), nullable=True)
    home_pitcher8_birthplace = Column(String(200), nullable=True)
    home_pitcher9_name = Column(String(200), nullable=True)
    home_pitcher9_birthdate = Column(String(200), nullable=True)
    home_pitcher9_birthplace = Column(String(200), nullable=True)    

